{
 "title": "Lake Indexer",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "chain_id", "label": "Chain", "query": "mainnet,testnet,betanet" }
  ]
 },
 "panels": [
  {
   "title": "Indexed Blocks per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(near_indexer_streaming_current_block_height{node_id=~\".*$chain_id-lake-node-.*\"}[$__rate_interval])",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Sync status",
   "type": "timeseries",
   "description": "Show the node sync status. Ideal is zero",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "near_sync_status{chain_id=\"$chain_id\", node_id=~\".*${chain_id}-lake-node.*\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Lake Indexer binary updates",
   "type": "piechart",
   "description": "In this section we are trying to keep the info about the up-to-date state of the Lake Indexers Deployments",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(build, release) (near_lake_build_info{chain_id=\"$chain_id\", node_id=~\"$chain_id-lake-node.*\"})",
     "legendFormat": "{{release}} (nearcore-{{build}})"
    }
   ]
  },
  {
   "title": "Seconds behind Network",
   "type": "stat",
   "description": "Time behind the network",
   "gridPos": { "h": 9, "w": 12, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(scalar(max(near_final_block_height{chain_id=\"$chain_id\", role=\"rpc\"})) - near_indexer_streaming_current_block_height{node_id=~\".*${chain_id}-lake-node.*\"}) / rate(near_blocks_processed{node_id=~\".*${chain_id}-lake-node.*\"}[$__rate_interval])\n",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "build_streamer_message",
   "type": "histogram",
   "description": "Represents the time taken by `build_streamer_message` function. The units are to be figured out",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 9 },
   "targets": [
    {
     "expr": "near_indexer_build_streamer_message_time_sum{chain_id=\"$chain_id\", node_id=~\"$chain_id-lake-node.*\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Last Indexed Block Height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "near_indexer_streaming_current_block_height{node_id=~\".*$chain_id-lake-node-.*\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Blocks behind Network",
   "type": "timeseries",
   "description": "We compare the current indexer block with the OPTIMISTIC block from the RPC role. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "scalar(max(near_final_block_height{chain_id=\"$chain_id\", role=\"rpc\"})) - near_indexer_streaming_current_block_height{node_id=~\".*${chain_id}-lake-node.*\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "up{node_id=~\".*$chain_id-lake-node-.*\", job=\"gce_machine_metrics\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Blocks indexed by instance",
   "type": "timeseries",
   "description": "This metric is expected to grow, resets mean the indexer was restarted",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "near_lake_block_done_total{chain_id=\"$chain_id\", node_id=~\"$chain_id-lake-node.*\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Put object Retries Rate",
   "type": "timeseries",
   "description": "Shows the put object to S3 error number (retries).",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
   "targets": [
    {
     "expr": "rate(near_lake_block_retry_count_total{chain_id=\"$chain_id\", node_id=~\"$chain_id-lake-node.*\"}[$__rate_interval])",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round((1 - (node_filesystem_avail_bytes{node_id=~\".*${chain_id}-lake-node-.*\", fstype=\"ext4\"} / node_filesystem_size_bytes)) * 100, 0.1)",
     "legendFormat": "{{node_id}} - {{device}}"
    }
   ]
  },
  {
   "title": "Num of blocks in past walk",
   "type": "timeseries",
   "description": "Represents how far it has to go in past to find the local delayed receipt. Directly affects on the `build_streamer_message` time. No data - ideal, closer to zero the better",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "near_indexer_local_receipt_lookup_in_history_blocks_back{chain_id=\"$chain_id\", node_id=~\"$chain_id-lake-node.*\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  }
 ]
}